### ISSUE TITLE
Ability to convert multiple times?

### ISSUE THREAD

**Issue by Jonovono** [seatgeek/sixpack#258] opened 2016-12-08 20:30 UTC
Hi. I am wondering if it's possible for one user to convert multiple times for a single experiment? I don't see a way to do this. Perhaps this doesn't really make sense but I want to be able to take into consideration the # of times a user does something.

Thanks.

**Comment by EliFinkelshteyn** [comment] 2016-12-22 22:43
Duplicate of https://github.com/seatgeek/sixpack/issues/238?

**Closed** 2016-12-22 22:48 UTC
