### ISSUE TITLE
dashboard UI broken

### ISSUE THREAD

**Issue by aryarohit07** [seatgeek/sixpack#261] opened 2017-01-10 13:27 UTC
First of all, thanks for a great library.

But I am unable to load dashboard properly.
<img width="1015" alt="screen shot 2017-01-10 at 6 55 38 pm" src="https://cloud.githubusercontent.com/assets/4436955/21807851/a11079e0-d766-11e6-81d3-40b68aa2460e.png">

Can you please help me out on this?

**Comment by josegonzalez** [comment] 2017-01-10 18:07
Duplicate of #260, which we'd accept a pull request for :)

**Closed by josegonzalez** 2017-01-10 18:07 UTC
